User/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from django.contrib.auth.views import LoginView, LogoutView

from User.apps import UserConfig
from User.views import RegisterView


app_name = UserConfig.name

urlpatterns = [
    path("register_user/", RegisterView.as_view(), name="register_user"),
    path('login/', LoginView.as_view(template_name='User/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("obtain/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("refresh/", TokenRefreshView.as_view(), name="token_refresh"),
]

config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="API Documentation",
        default_version='v1',
        description="Your API description",
        terms_of_service="https://www.example.com/policies/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/", include('CarBlog.urls', namespace='cars')),
    path("user/", include('User.urls', namespace='user')),
    path('', include('CarBlogFrontend.urls', namespace='carblog')),
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += staticfiles_urlpatterns()

User/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None

    USERNAME_FIELD = 'email'
   
    email = models.EmailField(unique=True, verbose_name="почта", null=False, blank=False)

    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

User/forms.py
from django.contrib.auth.forms import UserCreationForm
from User.models import User


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2')

User/views.py
from django.shortcuts import render
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetView
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from User.models import User
from User.forms import RegisterForm


class RegisterView(CreateView):
    """
    Контролер для регистрации пользователя.
    """
    model = User
    form_class = RegisterForm
    template_name = 'User/register.html'
    success_url = reverse_lazy('user:login')

User/templates/User/logged_out.html
{% extends "CarBlog/index.html" %}

{% block content %}
    <form action="{% url 'user:logout' %}" method="post">
        {% csrf_token %} 
        <button type="submit">Logout</button>
    </form>
{% endblock %}

User/templates/User/login.html
{% extends "CarBlog/index.html" %}

{% block content %}

<body>

    <div align="center">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="catd-header">
                <h3 class="card-title">Вход</h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success"> Войти </button>
            </div>

        </form>
    </div>


</body>


{% endblock %}

User/templates/User/register.html
{% extends "CarBlog/index.html" %}

{% block content %}

<body>

<div align="center">
    <form class="col-6" method="post" enctype="multipart/form-data">
        <div class="card ">
            <div class="card-header">
            <h3 class="card-title">Регистрация </h3>
        </div>
        <div class="card-body">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success"> Зарегистрироваться! </button>
        </div>
    </form>
</div>


</body>


{% endblock %}