CarBlog/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from CarBlog.apps import CarblogConfig
from CarBlog.views import CarViewSet, CommentView


app_name = CarblogConfig.name

router = DefaultRouter()
router.register(r'cars', CarViewSet, basename='cars')

urlpatterns = [
    path("cars/<int:pk>/comments/", CommentView.as_view(), name="comments"),
] + router.urls

CarBlogFrontend/urls.py
from django.urls import path
from CarBlogFrontend.views import CarListView, CarCreateView, CarTemplateView, CarUpdateView, CarDeleteView
from CarBlogFrontend.apps import CarblogfrontendConfig


app_name = CarblogfrontendConfig.name

urlpatterns = [
    path("main/", CarListView.as_view(), name="main"),
    path("create_car/", CarCreateView.as_view(), name="create_car"),
    path("car/<int:pk>/", CarTemplateView.as_view(), name="car"),
    path("update_car/<int:pk>", CarUpdateView.as_view(), name="update_car"),
    path("delete_car/<int:pk>", CarDeleteView.as_view(), name="delete_car"), 
]

User/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from django.contrib.auth.views import LoginView, LogoutView

from User.apps import UserConfig
from User.views import RegisterView


app_name = UserConfig.name

urlpatterns = [
    path("register_user/", RegisterView.as_view(), name="register_user"),
    path('login/', LoginView.as_view(template_name='User/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("obtain/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("refresh/", TokenRefreshView.as_view(), name="token_refresh"),
]

config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="API Documentation",
        default_version='v1',
        description="Your API description",
        terms_of_service="https://www.example.com/policies/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/", include('CarBlog.urls', namespace='cars')),
    path("user/", include('User.urls', namespace='user')),
    path('', include('CarBlogFrontend.urls', namespace='carblog')),
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += staticfiles_urlpatterns()

CarBlog/models.py
from django.db import models
from User.models import User

class Car(models.Model):
    make = models.CharField(verbose_name="марка автомобиля", max_length=32)
    model = models.CharField(verbose_name="модель автомобиля", max_length=32)
    year = models.PositiveSmallIntegerField(verbose_name="год выпуска")
    description = models.TextField(verbose_name="описание автомобиля")
    created_at = models.DateTimeField(verbose_name="дата и время создания записи", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="дата и время последнего обновления записи", auto_now=True)
    owner = models.ForeignKey(User, verbose_name="пользователь, который создал запись", null=True, blank=True, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = 'автомобиль'
        verbose_name_plural = 'автомобили'


class Comment(models.Model):
    content = models.TextField(verbose_name="содержание комментария")
    created_at = models.DateTimeField(verbose_name="дата и время создания комментария", auto_now_add=True)
    car = models.ForeignKey(Car, verbose_name="автомобиль к которому оставлен комментарий", null=True, blank=True, on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name="автор комментария", null=True, blank=True, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'

CarBlogFrontend/models.py
from django.db import models

# Create your models here.

CarBlogFrontend/forms.py
from django import forms

from CarBlog.models import Car, Comment


class CarForm(forms.ModelForm):

    class Meta:
        model = Car
        fields = '__all__'
        exclude = ('owner',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'
        exclude=('author', 'car',)
        

CarBlog/views.py
from django.shortcuts import render
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.generics import GenericAPIView, get_object_or_404
from rest_framework.renderers import TemplateHTMLRenderer

from CarBlog.serializers import CarSerializer, CommentSerializer
from CarBlog.models import Car, Comment
from User.permissions import IsOwner



class CarViewSet(viewsets.ModelViewSet):
    """
    Вьюсет реализующий CRUD для модели авто.
    """
    queryset = Car.objects.all()
    serializer_class = CarSerializer

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)

    def get_permissions(self):
        if self.action == 'create':
            self.permission_classes = [IsAuthenticated,]
        elif self.action == 'list':
            self.permission_classes = [AllowAny]
        elif self.action == 'destroy':
            self.permission_classes = [IsAuthenticated, IsOwner]
        elif self.action == 'update':
            self.permission_classes = [IsAuthenticated, IsOwner]
        elif self.action == 'retrieve':
            self.permission_classes = [AllowAny]

        return [permission() for permission in self.permission_classes]

class CommentView(GenericAPIView):
    """
    Контролеры для создания и получения комментариев.
    """
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

    def get(self, request, *args, **kwargs):
        car_pk = self.kwargs.get('pk')
        car_item = get_object_or_404(Car, pk=car_pk)
        data = Comment.objects.filter(car=car_item)
        serializer = CommentSerializer(data, many=True)
        return Response(serializer.data)

    def post(self, request, *args, **kwargs):
        car_pk = self.kwargs.get('pk')
        car_item = get_object_or_404(Car, pk = car_pk)
        serializer = CommentSerializer(data=request.data)
        if serializer.is_valid():
            user = self.request.user
            serializer.save(car=car_item, author=user)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    

CarBlogFrontend/views.py
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from CarBlog.models import Car, Comment
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from CarBlogFrontend.forms import CarForm, CommentForm
from django.shortcuts import render, redirect


class CarListView(ListView):
    """
    Контролер для отображения всех авто через интерфейс.
    """
    model = Car
    template_name = 'CarBlog/CarBlog.html'


class CarCreateView(LoginRequiredMixin, CreateView):
    """
    Контролер для создания авто через интерфейс.
    """
    model = Car
    form_class = CarForm
    success_url = reverse_lazy('carblog:main')
    template_name = 'CarBlog/car_form.html'

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        car = form.save()
        car.owner = self.request.user
        car.save()
        return super().form_valid(form)


class CarUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контролер для изменения авто через интерфейс.
    """
    model = Car
    form_class = CarForm
    success_url = reverse_lazy('carblog:main')
    login_url = reverse_lazy('user:login')
    template_name = 'CarBlog/car_form.html'
    

class CarDeleteView(LoginRequiredMixin, DeleteView):
    """
    Контролер для удаления авто через интерфейс.
    """
    success_url = reverse_lazy('carblog:main')
    login_url = reverse_lazy('user:login')
    redirect_field_name = 'redirect_to'
    model = Car
    template_name='CarBlog/car_delete_confirm.html'


class CarTemplateView(LoginRequiredMixin, TemplateView):
    """
    Контролер для отображения одного авто и дабавления комментарий к нему через интерфейс.
    """
    model = Comment
    login_url = reverse_lazy('user:login')
    redirect_field_name = 'redirect_to'
    template_name = 'CarBlog/car.html'

    def get(self, request, pk):
        car_item = Car.objects.get(pk=pk)
        context = {'object': car_item, 'comments': Comment.objects.filter(car=car_item), 'comment_form':CommentForm()}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        car_item = Car.objects.get(pk=self.kwargs['pk'])
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = self.request.user
            comment.car = car_item
            comment.save()
            return redirect('carblog:car', pk=car_item.pk)
        return self.get(request, car_item.pk)
        

CarBlogFrontend/templates/CarBlog/CarBlog.html
{% extends "CarBlog/index.html" %}

{% block content %}
<body>
    <div class="mx-auto row">
        {% for car_item in object_list %}
            <div class="col-md-4 text-center">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ car_item.make }} - {{ car_item.model }}</h4>
                    </div>
                    <div class="card-body">
                        <p>
                            {{ car_item.description|truncatechars:100 }}
                        </p>
                        <a type="button" class="btn btn-lg btn-block btn-outline-primary" href={% url "carblog:car" pk=car_item.pk %} >Подробнее</a>
                        {% if user.is_authenticated %}
                            {% if user.email == car_item.owner.email %}
                                <a type="button" class="btn btn-warning" href={% url "carblog:update_car" pk=car_item.pk %} >Изменить</a>
                                <a type="button" class="btn btn-danger" href={% url "carblog:delete_car" pk=car_item.pk %} >Удалить</a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</body>

{% endblock %}

CarBlogFrontend/templates/CarBlog/car.html
{% extends "CarBlog/index.html" %}

{% block content %}

<body>
    <div class="container my-5">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <h1>{{ object.make }} - {{ object.model }} </h1>
                        <p class="lead">{{ object.description }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container my-5 py-5">
        <div class="row d-flex justify-content-center">
            <div class="col-md-12 col-lg-10 col-xl-8">
                {% for comment_item in comments %}
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-start align-items-center">
                                <div>
                                    <h6 class="fw-bold text-primary mb-1">{{comment_item.author.first_name}} {{comment_item.author.last_name}}</h6>
                                    <p class="text-muted small mb-0">
                                        Опубликованно - {{comment_item.created_at}}
                                    </p>
                                </div>
                            </div>
                            <p class="mt-3 mb-4 pb-2">
                                {{ comment_item.content }}
                            </p>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% if user.is_authenticated %}
                <form method="post">    
                    {% csrf_token %}
                    <div class="card-footer py-3 border-0">
                        <div data-mdb-input-init class="form-outline w-100">
                            {{comment_form.as_p}}
                            <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-sm">Комментировать</button>
                        </div>
                    </div>
                </form>    
            {% endif %}
        </div>
    </div>
</body>

{% endblock %}

CarBlogFrontend/templates/CarBlog/car_delete_confirm.html
{% extends "CarBlog/index.html" %}

{% block content %}

<div class="col-12 text-center">
    <div class="row">
        <div align="center"> 
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Удалить авто {{ object.make }} - {{ object.model }}?</p>
                            <button class="btn btn-danger" type="submit">Подтвердить</button>
                            <a href={% url "carblog:main" %} class="btn btn-light">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

CarBlogFrontend/templates/CarBlog/car_form.html
{% extends "CarBlog/index.html" %}

{% block content %}
<body>
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div align="center">
                <div class="col-3">
                    <div class="card">
                        <div class="card-body">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit">Создать авто!</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</body>
{% endblock %}

CarBlogFrontend/templates/CarBlog/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="autor" content="">
    <title>Машинки</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
</head>

{% include "CarBlog/includes/inc_menu.html" %}

{% block content %}
{% endblock %}

</html>